### ISSUE TITLE
offline address generator

### ISSUE THREAD

**Issue by digitron-lisk** [lisksnake/offlineLiskTools#1]
Hi Thomas,

ich habe noch was zu deinem Super Tool dazugestrickt, einen Random-Secret-Generator, der hatte für meine Zwecke gefehlt. Ich bin Github Anfänger, wie kann ich das beitragen? Branch, Fork, oder du integrierst es?

Gruss
Gerald

[offlineGenerateSecrets_Address_PublicKey.zip](https://github.com/lisksnake/offlineLiskTools/files/1399080/offlineGenerateSecrets_Address_PublicKey.zip)

**Comment by lisksnake** [comment]
Added it.

Vielen Dank.
